[package]
name = "gnomad_to_parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow="57"
parquet="57"
flate2="1"
anyhow="1.0"
log = "0.4"
env_logger="0.11"
xxhash-rust={version="0.8",features=["xxh64"]}
tikv-jemallocator = "0.6"